### ISSUE TITLE
Issue with GraphicsMagick/ImageMagick

### ISSUE THREAD

**Issue by andrewfan** [bguiz/ember-sprite#20]
@bguiz Hello, i tried to use this addon, after starting the server i got 
```
Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/projects/ember-sprite/node_modules/broccoli-sprite/node_modules/node-sprite-generator/node_modules/gm/lib/command.js:299:14)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```
maybe you know how to fix it?

**Comment by abhilashlr** [comment]
This helped me solve the problem:
**http://stackoverflow.com/a/17846596**

**Comment by bguiz** [comment]
You will need graphics magick binaries available on your path, @abhilashlr 's solution looks about right.
