### ISSUE TITLE
Path or pattern "assets/undefined.css" did not match any files [string exception]

### ISSUE THREAD

**Issue by jmonster** [bguiz/ember-sprite#3]
I'm unable to get this to work on ember-cli v0.1.2. See below:

```bash
jmonster:foo/ (sprites✗) $ ember server                                                                                                                                                [12:39:25]
version: 0.1.2
spriteTree { inputTrees:
   [ { inputTree:
        { inputTree: 'app',
          options:
           { srcDir: '/',
             files: [ 'index.html' ],
             destDir: '/' } },
       configTree:
        { inputTree:
           { _inputTreeCacheHash: [],
             _shouldBeIgnoredCache: {},
             destDir: '/Users/jmonster/Documents/foo/tmp/caching-writer-dest-dir_C60rKh.tmp',
             env: 'development',
             tests: true,
             project:
              { root: '/Users/jmonster/Documents/foo',
                pkg:
                 { name: 'foo',
                   version: '0.0.0',
                   private: true,
                   directories: [Object],
                   scripts: [Object],
                   repository: 'https://github.com/stefanpenner/ember-cli',
                   engines: [Object],
                   author: '',
                   license: 'MIT',
                   devDependencies: [Object] },
                addonPackages:
                 { 'tests-server-middleware': [Object],
                   'history-support-middleware': [Object],
                   'serve-files-middleware': [Object],
                   'proxy-server-middleware': [Object],
                   'broccoli-asset-rev': [Object],
                   'ember-cli-content-security-policy': [Object],
                   'ember-cli-ic-ajax': [Object],
                   'ember-cli-inject-live-reload': [Object],
                   'ember-cli-qunit': [Object],
                   'ember-data': [Object],
                   'ember-export-application-global': [Object],
                   'ember-sprite': [Object] },
                liveReloadFilterPatterns: [],
                bowerDirectory: 'bower_components',
                addons:
                 [ [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object] ],
                _addonsInitialized: true },
             inputTrees: [ 'config' ],
             filterFromCache: { include: [], exclude: [] },
             options:
              { env: 'development',
                tests: true,
                project:
                 { root: '/Users/jmonster/Documents/foo',
                   pkg: [Object],
                   addonPackages: [Object],
                   liveReloadFilterPatterns: [],
                   bowerDirectory: 'bower_components',
                   addons: [Object],
                   _addonsInitialized: true } } },
          options: { srcDir: '/', destDir: 'foo/config' } },
       options:
        { configPath: 'foo/config/environments/development.json',
          files: [ 'index.html' ],
          patterns:
           [ { match: /\{\{EMBER_ENV\}\}/g,
               replacement: [Function: calculateEmberENV] },
             { match: /\{\{APP_CONFIG\}\}/g,
               replacement: [Function: calculateAppConfig] },
             { match: /\{\{content-for ['"](.+)["']\}\}/g,
               replacement: [Function] },
             { match: /\{\{MODULE_PREFIX\}\}/g,
               replacement: [Function: calculateModulePrefix] } ] } },
     { inputTrees:
        [ { inputTree:
             { inputTrees:
                [ [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object] ],
               options:
                { overwrite: true,
                  description: 'TreeMerger (appAndDependencies)' },
               description: 'TreeMerger (appAndDependencies)' },
            inputFiles:
             [ 'vendor/ember-cli/vendor-prepend.js',
               'bower_components/loader.js/loader.js',
               'bower_components/jquery/dist/jquery.js',
               'bower_components/handlebars/handlebars.js',
               'bower_components/ember/ember.js',
               'bower_components/ember-cli-shims/app-shims.js',
               'bower_components/ember-resolver/dist/modules/ember-resolver.js',
               'bower_components/ember-load-initializers/ember-load-initializers.js',
               'vendor/ic-ajax/dist/named-amd/main.js',
               'bower_components/ember-data/ember-data.js',
               'vendor/addons.js' ],
            outputFile: '/assets/vendor.js',
            separator: '\n;',
            cache: {},
            cachedConcatenatedOutputHash: null },
          { inputTree:
             { inputTrees: [ [Object], [Object] ],
               options: {},
               description: undefined },
            inputFiles:
             [ 'assets/foo.js',
               'vendor/ember-cli/app-suffix.js' ],
            outputFile: '/assets/foo.js',
            cache: {},
            cachedConcatenatedOutputHash: null } ],
       options: {},
       description: undefined },
     { inputTrees:
        [ { inputTree:
             { inputTrees:
                [ [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object] ],
               options: { description: 'TreeMerger (stylesAndVendor)' },
               description: 'TreeMerger (stylesAndVendor)' },
            _includeFileCache: {},
            _destinationPathCache: {},
            _tmpDir: '/Users/jmonster/Documents/foo/tmp/funnel-dest_FX2AJZ.tmp',
            srcDir: '/app/styles',
            getDestinationPath: [Function],
            destDir: '/',
            destPath: '/Users/jmonster/Documents/foo/tmp/funnel-dest_FX2AJZ.tmp' },
          { inputTree:
             { inputTrees:
                [ [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object],
                  [Object] ],
               options: { description: 'TreeMerger (stylesAndVendor)' },
               description: 'TreeMerger (stylesAndVendor)' },
            inputFiles: [ 'vendor/addons.css' ],
            outputFile: '/assets/vendor.css',
            description: 'concatFiles - vendorStyles',
            cache: {},
            cachedConcatenatedOutputHash: null } ],
       options: { description: 'styles' },
       description: 'styles' },
     { inputTrees:
        [ { inputTree:
             { inputTrees: [ [Object], [Object] ],
               options: { description: 'TreeMerger (ExternalTree)' },
               description: 'TreeMerger (ExternalTree)' },
            options:
             { srcDir: 'bower_components/ember-qunit-notifications',
               files: [ 'passed.png' ],
               destDir: 'assets' } },
          { inputTree:
             { inputTrees: [ [Object], [Object] ],
               options: { description: 'TreeMerger (ExternalTree)' },
               description: 'TreeMerger (ExternalTree)' },
            options:
             { srcDir: 'bower_components/ember-qunit-notifications',
               files: [ 'failed.png' ],
               destDir: 'assets' } } ],
       options: { description: 'TreeMerger (otherAssetTrees)' },
       description: 'TreeMerger (otherAssetTrees)' },
     { inputTrees:
        [ { inputTrees: [], options: {} },
          { inputTrees: [], options: {} },
          { inputTrees: [], options: {} },
          { inputTrees: [], options: {} },
          { inputTrees: [], options: {} },
          'public' ],
       options: { overwrite: true },
       description: undefined },
     { inputTree:
        { inputTree: 'tests',
          options:
           { srcDir: '/',
             files: [ 'index.html' ],
             destDir: '/tests' } },
       configTree:
        { inputTree:
           { _inputTreeCacheHash: [],
             _shouldBeIgnoredCache: {},
             destDir: '/Users/jmonster/Documents/foo/tmp/caching-writer-dest-dir_C60rKh.tmp',
             env: 'development',
             tests: true,
             project:
              { root: '/Users/jmonster/Documents/foo',
                pkg:
                 { name: 'foo',
                   version: '0.0.0',
                   private: true,
                   directories: [Object],
                   scripts: [Object],
                   repository: 'https://github.com/stefanpenner/ember-cli',
                   engines: [Object],
                   author: '',
                   license: 'MIT',
                   devDependencies: [Object] },
                addonPackages:
                 { 'tests-server-middleware': [Object],
                   'history-support-middleware': [Object],
                   'serve-files-middleware': [Object],
                   'proxy-server-middleware': [Object],
                   'broccoli-asset-rev': [Object],
                   'ember-cli-content-security-policy': [Object],
                   'ember-cli-ic-ajax': [Object],
                   'ember-cli-inject-live-reload': [Object],
                   'ember-cli-qunit': [Object],
                   'ember-data': [Object],
                   'ember-export-application-global': [Object],
                   'ember-sprite': [Object] },
                liveReloadFilterPatterns: [],
                bowerDirectory: 'bower_components',
                addons:
                 [ [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object],
                   [Object] ],
                _addonsInitialized: true },
             inputTrees: [ 'config' ],
             filterFromCache: { include: [], exclude: [] },
             options:
              { env: 'development',
                tests: true,
                project:
                 { root: '/Users/jmonster/Documents/foo',
                   pkg: [Object],
                   addonPackages: [Object],
                   liveReloadFilterPatterns: [],
                   bowerDirectory: 'bower_components',
                   addons: [Object],
                   _addonsInitialized: true } } },
          options: { srcDir: '/', destDir: 'foo/config' } },
       options:
        { configPath: 'foo/config/environments/test.json',
          files: [ 'tests/index.html' ],
          env: 'test',
          patterns:
           [ { match: /\{\{EMBER_ENV\}\}/g,
               replacement: [Function: calculateEmberENV] },
             { match: /\{\{APP_CONFIG\}\}/g,
               replacement: [Function: calculateAppConfig] },
             { match: /\{\{content-for ['"](.+)["']\}\}/g,
               replacement: [Function] },
             { match: /\{\{MODULE_PREFIX\}\}/g,
               replacement: [Function: calculateModulePrefix] } ] } },
     { inputTrees:
        [ { inputTree:
             { inputTrees: [ [Object], [Object] ],
               options: {},
               description: undefined },
            inputFiles:
             [ 'vendor/ember-cli/test-support-suffix.js',
               'assets/test-support.js' ],
            outputFile: '/assets/test-support.js',
            cache: {},
            cachedConcatenatedOutputHash: null },
          { inputTree:
             { inputTrees: [ [Object], [Object] ],
               options: { description: 'TreeMerger (ExternalTree)' },
               description: 'TreeMerger (ExternalTree)' },
            inputFiles: [ 'bower_components/qunit/qunit/qunit.css' ],
            outputFile: '/assets/test-support.css',
            cache: {},
            cachedConcatenatedOutputHash: null },
          { inputTree:
             { inputTrees: [ [Object], [Object] ],
               options: { description: 'TreeMerger (ExternalTree)' },
               description: 'TreeMerger (ExternalTree)' },
            options:
             { files: [ 'test-loader.js' ],
               srcDir: '/bower_components/ember-cli-test-loader',
               destDir: '/assets/' } },
          { inputTree:
             { dir: '/Users/jmonster/Documents/foo/node_modules/ember-cli/lib/broccoli',
               description: 'Unwatched - /Users/jmonster/Documents/foo/node_modules/ember-cli/lib/broccoli' },
            options:
             { files: [ 'testem.js' ],
               srcDir: '/',
               destDir: '/' } } ],
       options:
        { overwrite: true,
          description: 'TreeMerger (testFiles)' },
       description: 'TreeMerger (testFiles)' } ],
  options:
   { overwrite: true,
     description: 'TreeMerger (allTrees)' },
  description: 'TreeMerger (allTrees)' }
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Running BroccoliSprite updateCache
srcDir /Users/jmonster/Documents/foo/tmp/static_compiler-tmp_dest_dir-BAGQ12pv.tmp
destDir /Users/jmonster/Documents/foo/tmp/broccoli_sprite-tmp_cache_dir-N7bNUmck.tmp
files [ '/Users/jmonster/Documents/foo/tmp/static_compiler-tmp_dest_dir-BAGQ12pv.tmp/images/sprites/**/*.png' ]
Options:  { debug: true,
  src: [ '/Users/jmonster/Documents/foo/tmp/static_compiler-tmp_dest_dir-BAGQ12pv.tmp/images/sprites/**/*.png' ],
  spritePath: '/Users/jmonster/Documents/foo/tmp/broccoli_sprite-tmp_cache_dir-N7bNUmck.tmp/assets/sprites.png',
  stylesheetPath: '/Users/jmonster/Documents/foo/tmp/broccoli_sprite-tmp_cache_dir-N7bNUmck.tmp/assets/sprites.css',
  stylesheet: 'css',
  stylesheetOptions:
   { prefix: 'icon-',
     spritePath: '/assets/sprites.png',
     pixelRatio: 2 },
  layoutOptions: { padding: 2 } }
spritePath /Users/jmonster/Documents/foo/tmp/broccoli_sprite-tmp_cache_dir-N7bNUmck.tmp/assets/sprites.png
stylesheetPath /Users/jmonster/Documents/foo/tmp/broccoli_sprite-tmp_cache_dir-N7bNUmck.tmp/assets/sprites.css
Sprite generated!
Path or pattern "assets/undefined.css" did not match any files [string exception]
Error: Path or pattern "assets/undefined.css" did not match any files [string exception]
    at /Users/jmonster/Documents/foo/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:34:15
    at $$$internal$$tryCatch (/Users/jmonster/Documents/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/Users/jmonster/Documents/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/Users/jmonster/Documents/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$$internal$$publishRejection (/Users/jmonster/Documents/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:395:7)
    at $$rsvp$asap$$flush (/Users/jmonster/Documents/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:419:13)
```

**Comment by bguiz** [comment]
Housekeeping close - thanks for fixing!
